### ISSUE TITLE
bad callback: <bound method LineFollower.

### ISSUE THREAD

**Issue by mengchaoheng** [COONEO/neor_mini#3]
```
[ERROR] [1650089385.266396, 7264.469000]: bad callback: <bound method LineFollower.camera_callback of <__main__.LineFollower object at 0xffff9eb0d190>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/parallels/neor_mini/mini_sim18_ws/src/neor_mini_linetrack/scripts/line_follower_object.py", line 32, in camera_callback
    crop_img = cv_image[(height)/4 + descentre:(height)/4 + (descentre+rows_to_watch)][1:width]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by mengchaoheng** [comment]
in chapter2
